[phases.setup]
nixPkgs = ["python311", "libGL", "mesa", "glib", "xorg.libXext", "xorg.libSM", "xorg.libXrender", "fontconfig"]
aptPkgs = ["libgl1-mesa-dev", "libglib2.0-0", "build-essential", "python3-dev"]

[start]
cmd = "LD_LIBRARY_PATH=/nix/store/*/lib:$LD_LIBRARY_PATH gunicorn app:app"
