[phases.setup]
nixPkgs = ["python311", "libGL", "mesa", "glib", "xorg.libXext", "xorg.libSM", "xorg.libXrender", "fontconfig"]
aptPkgs = ["libgl1-mesa-dev", "libglib2.0-0", "build-essential", "python3-dev"]

[start]
cmd = "export LD_LIBRARY_PATH=$(find /nix/store -name 'lib' -type d | tr '\n' ':')$LD_LIBRARY_PATH && gunicorn app:app --bind 0.0.0.0:$PORT"
