[phases.setup]
nixPkgs = ["python311", "libGL", "glib", "xorg.libXext", "xorg.libSM", "xorg.libXrender", "fontconfig", "mesa"]
aptPkgs = ["libgl1-mesa-dev", "libglib2.0-0", "build-essential", "python3-dev"]
